default: &default
  cloud_name: Rails.application.secrets.clodinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_file_support: false

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default