default: &default
  fcm_server_key: <%= ENV['HAIRFOLIO_FCM_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  clodinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  aws_access_key_id: <%= ENV['HAIRFOLIO_AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['HAIRFOLIO_AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['HAIRFOLIO_AWS_BUCKET_NAME'] %>
  hairfolio_frontend_url: <%= ENV['HAIRFOLIO_URL'] %>
  master_key: <%= ENV['MASTER_KEY'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_redirect_url: <%= ENV['FACEBOOK_REDIRECT_URL'] %>
  insta_client_id: <%= ENV['INSTAGRAM_CLIENT_ID'] %>
  insta_redirect_url: <%= ENV['INSTAGRAM_REDIRECT_URL'] %>
  cloud_preset: <%= ENV['CLOUDINARY_PRESET'] %>
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default